### ISSUE TITLE
undefined attribute values are converted to strings

### ISSUE THREAD

**Issue by mathiasvr** [substack/hyperx#27]
When attribute values are `undefined` or `null` they are appended as strings 'undefined' or 'null'.

For example this code:
```javascript
var none // unassigned
hx`<li.item class=${none}>...</li>`
```
Will result in html like this:
```html
<li class="item undefined">...</li>
```
Whereas `virtual-hyperscript` will ignore the value and not add it to the class list.

I'm not sure if this is the correct behavior, but i expected it to do the same as `virtual-hyperscript`. This can easily be achieved by the developer by supplying a custom concat function, or simply ensuring that undefined values are never used, but i think this should be handled by default?

If it is a bug, I think it can be fixed in the [concat method](https://github.com/substack/hyperx/blob/2.0.4/index.js#L13), by making undefined parameters default to empty strings (''). However maybe there is a better way to do it?

**Comment by slaskis** [comment]
I agree. 

Ideally the renderers would be responsible for interpreting the attribute values (such as converting to string or whatever) and have the attribute value set to whatever was passed in through the `${}`.

**Comment by jbucaran** [comment]
I thought this was fixed according to https://github.com/substack/hyperx/issues/8.

**Comment by mathiasvr** [comment]
@jbucaran Seems like it only works for tag content and not attributes?

**Comment by Ramblurr** [comment]
I can confirm it still exists.

```js
const imgsrc = undefined;
const img = hx`<img src=${imgsrc}/>`
```

This causes chrome to make http requests to `/undefined`

**Comment by vladimirkosmala** [comment]
I agree with this issue, it is actually implemented with Babel/JSX.
Those falsy values should be forgotten (not numbers):
- false
- null
- undefined
- empty string

Let's compare:
```js
❌ html`<input value="${data.value ? data.value : ''}" />`
✅ html`<input value="${data.value}" />`
```
Declarative conditional
```js
❌ html`<div>${data.alert ? html`<x-alert />` : ''}</div>`
✅ html`<div>${data.alert && html`<x-alert />}</div>`
```
Declarative switch case with three ternary operators
```js
❌ html`<div>${data.option === 1 ? html`<x-option1 />` : (data.option === 2 ? html`<x-option2 />` : html`<x-option3 />`)}</div>`
✅ html`<div>
${data.option === 1 && html`<x-option1 />}
${data.option === 2 && html`<x-option2 />}
${data.option === 3 && html`<x-option3 />}
</div>`
```
The idea is to keep it declarative (no if/else/swtich) and lisible as possible.

It could create a breaking change so v3 is a possibility.
An other one is to provide this as an option.
What do you think?
